version: 2

sources:
  - name: raw
    schema: raw
    tables:
      - name: requests
        columns:
          - name: users_id
            tests:
              - not_null
          - name: id
            tests:
              - unique
              - not_null
          - name: requests_date
            tests:
              - unique
          - name: request_uri
            tests:
              - not_null
